server:
  port: 9000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql:url?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: mysql123
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 100000
      login-timeout: 5
      max-lifetime: 120000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  redis:
    host: url
    port: 6379
    timeout: 5000
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1